# Generated by Django 2.2.6 on 2019-11-02 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0003_auto_20191103_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Submissions',
        ),
    ]
