# Generated by Django 2.2.6 on 2019-11-02 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Submitted At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 17, 19, 2, 612640, tzinfo=utc), verbose_name='Updated At'),
            preserve_default=False,
        ),
    ]
