# Generated by Django 2.2.6 on 2019-11-02 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20191102_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('repo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='link',
            field=models.URLField(default='https://github.com', verbose_name='GitHub link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='merged_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 18, 48, 40, 559229, tzinfo=utc), verbose_name='Submitted At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.IntegerField(choices=[(10, 10), (15, 15), (25, 25), (30, 30), (50, 50)], default=10),
            preserve_default=False,
        ),
    ]
