# Generated by Django 2.2.6 on 2019-11-02 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0004_auto_20191103_0020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repositories',
            new_name='Repository',
        ),
        migrations.RenameModel(
            old_name='Submissions',
            new_name='Submission',
        ),
    ]
