# Generated by Django 2.2.6 on 2019-11-08 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20191103_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 8, 16, 16, 12, 887676, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
