# Generated by Django 2.2.6 on 2019-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_submission_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.IntegerField(choices=[(5, 'extra'), (10, 'very easy'), (15, 'easy'), (25, 'medium'), (30, 'hard'), (50, 'pro'), (100, 'codeburst')]),
        ),
    ]
